export enum ChainAction {
  GET_TRANSACTION_STATUS = 'GET_TRANSACTION_STATUS',
  GET_CHAIN_NODES = 'GET_CHAIN_NODES',
  GET_BLOCK = 'GET_BLOCK',
  GET_WALLET = 'GET_WALLET',
  GET_NODE_SETTINGS = 'GET_NODE_SETTINGS',
  CREATE_TRANSACTION = 'CREATE_TRANSACTION',
  GET_MY_CHAIN = 'GET_MY_CHAIN',
  GET_SC_CODE = 'GET_SC_CODE',
  GET_SC_STATE = 'GET_SC_STATE',
}
