export enum ChainAction {
  GET_TRANSACTION_STATUS = 'GET_TRANSACTION_STATUS',
  GET_CHAIN_NODES = 'GET_CHAIN_NODES',
  GET_BLOCK_HASH = 'GET_BLOCK_HASH',
  GET_BLOCK = 'GET_BLOCK',
  GET_BLOCK_BY_HEIGHT = 'GET_BLOCK_BY_HEIGHT',
  GET_BLOCK_INFO = 'GET_BLOCK_INFO',
  GET_WALLET = 'GET_WALLET',
  GET_WALLET_SEQUENCE = 'GET_SEQUENCE',
  GET_NODE_SETTINGS = 'GET_NODE_SETTINGS',
  CREATE_TRANSACTION = 'CREATE_TRANSACTION',
  EXECUTE_CALL = 'EXECUTE_CALL',
  GET_MY_CHAIN = 'GET_MY_CHAIN',
  GET_SC_CODE = 'GET_SC_CODE',
  GET_SC_STATE = 'GET_SC_STATE',
  GET_SC_STATE_BY_KEY = 'GET_SC_STATE_BY_KEY',
  GET_LSTORE = 'GET_LSTORE'
}
