name: autodeploy-dev

on:
  push:
    branches: [develop]
  workflow_dispatch:

env:
  CI: true

jobs:
  publish-gpr-dev:
    name: Publish to GPR dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set Git User
        run: |
          git config --global user.name "Power DCloud"
          git config --global user.email "info@thepower.io"

      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"

      - name: Bootstrap lerna
        run: yarn lerna:init

      - name: Publish packages
        run: |
          yarn publish:canary
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMTOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
